# Generated by Django 4.0.4 on 2022-05-27 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='goods')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isDelete', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
            managers=[
                ('goods', django.db.models.manager.Manager()),
            ],
        ),
    ]
