# Generated by Django 4.0.4 on 2022-05-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('type', models.CharField(default='', max_length=20)),
                ('picture', models.ImageField(default='', upload_to='goods')),
                ('number', models.CharField(default='1', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsinfo')),
            ],
        ),
    ]
